---
ansible_user: ansible
ansible_ssh_private_key_file: ~/.ssh/lab_ansible

# ssh_hardening role
ssh_port: 22
ssh_password_authentication: false
ssh_permit_root_login: prohibit-password

# firewall role
firewall_open_ports:
  - 80/tcp
  - 443/tcp

# selinux role
selinux_state: enforcing
selinux_allow_reboot: false
