---
# Rules Section 1

- name: SCAN | 1.1.1.1 | Ensure cramfs kernel module is not available
  block:
  - name: SCAN | 1.1.1.1 | A | Ensure cramfs kernel module is not available
    shell: lsmod | grep 'cramfs'
    register: rule_1_1_1_1_a
    changed_when: false
    failed_when: false
  - name: SCAN | 1.1.1.1 | B | Ensure cramfs kernel module is not available
    shell: modprobe -n -v cramfs
    register: rule_1_1_1_1_b
    changed_when: false
    failed_when: false

  - set_fact:
      rule_1_1_1_1_result: true
    when: rule_1_1_1_1_a.rc != 0 and (rule_1_1_1_1_b.rc != 0 or 'install' in rule_1_1_1_1_b.stdout)
  - set_fact:
      all_results: "{{ all_results|combine({'1.1.1.1':rule_1_1_1_1_result|default(false)}) }}"
    when: rhel9cis_rule_1_1_1_1
    ignore_errors: true
    tags:
      - rule_1.1.1.1
      - filesystem
      - level1
      - scan
  
- name: SCAN | 1.1.1.2 | Ensure freevxfs kernel module is not available
  block:
  - name: SCAN | 1.1.1.2 | A | Ensure freevxfs kernel module is not available
    shell: lsmod | grep 'freevxfs'
    register: rule_1_1_1_2_a
    changed_when: false
    failed_when: false

  - name: SCAN | 1.1.1.2 | B | Ensure freevxfs kernel module is not available
    shell: modprobe -n -v freevsfs
    register: rule_1_1_1_2_b
    changed_when: false
    failed_when: false

  - set_fact:
      rule_1_1_1_2_result: true
    when: rule_1_1_1_2_a.rc != 0 and (rule_1_1_1_2_b.rc != 0 or 'install' in rule_1_1_1_2_b.stdout)
  - set_fact:
      all_results: "{{ all_results|combine({'1.1.1.2':rule_1_1_1_2_result|default(false)}) }}"
    when: rhel9cis_rule_1_1_1_2
    ignore_errors: true
    tags:
      - rule_1.1.1.2
      - filesystem
      - level1
      - scan

- name: SCAN | 1.1.1.3 | Ensure hfs kernel module is not available
  block:
  - name: SCAN | 1.1.1.3 | A | Ensure hfs kernel module is not available
    shell: lsmod | grep 'hfs'
    register: rule_1_1_1_3_a
    changed_when: false
    failed_when: false

  - name: SCAN | 1.1.1.3 | B | Ensure hfs kernel module is not available
    shell: modprobe -n -v hfs
    register: rule_1_1_1_3_b
    changed_when: false
    failed_when: false

  - set_fact:
      rule_1_1_1_3_result: true
    when: rule_1_1_1_3_a.rc != 0 and (rule_1_1_1_3_b.rc != 0 or 'install' in rule_1_1_1_3_b.stdout)
  - set_fact:
      all_results: "{{ all_results|combine({'1.1.1.3':rule_1_1_1_3_result|default(false)}) }}"
    when: rhel9cis_rule_1_1_1_3
    ignore_errors: true
    tags:
      - rule_1.1.1.3
      - filesystem
      - level1
      - scan

- name: SCAN | 1.1.1.4 | Ensure hfsplus kernel module is not available
  block:
  - name: SCAN | 1.1.1.4 | A | Ensure hfsplus kernel module is not available
    shell: lsmod | grep 'hfsplus'
    register: rule_1_1_1_4_a
    changed_when: false
    failed_when: false

  - name: SCAN | 1.1.1.4 | B | Ensure hfsplus kernel module is not available
    shell: modprobe -n -v hfsplus
    register: rule_1_1_1_4_b
    changed_when: false
    failed_when: false

  - set_fact:
      rule_1_1_1_4_result: true
    when: rule_1_1_1_4_a.rc != 0 and (rule_1_1_1_4_b.rc != 0 or 'install' in rule_1_1_1_4_b.stdout)
  - set_fact:
      all_results: "{{ all_results|combine({'1.1.1.4':rule_1_1_1_4_result|default(false)}) }}"
    when: rhel9cis_rule_1_1_1_4
    ignore_errors: true
    tags:
      - rule_1.1.1.4
      - filesystem
      - level1
      - scan

- name: SCAN | 1.1.1.5 | Ensure jffs2 kernel module is not available
  block:
  - name: SCAN | 1.1.1.5 | A | Ensure jffs2 kernel module is not available
    shell: lsmod | grep 'jffs2'
    register: rule_1_1_1_5_a
    changed_when: false
    failed_when: false

  - name: SCAN | 1.1.1.5 | B | Ensure jffs2 kernel module is not available
    shell: modprobe -n -v jffs2
    register: rule_1_1_1_5_b
    changed_when: false
    failed_when: false

  - set_fact:
      rule_1_1_1_5_result: true
    when: rule_1_1_1_5_a.rc != 0 and (rule_1_1_1_5_b.rc != 0 or 'install' in rule_1_1_1_5_b.stdout)
  - set_fact:
      all_results: "{{ all_results|combine({'1.1.1.5':rule_1_1_1_5_result|default(false)}) }}"
    when: rhel9cis_rule_1_1_1_5
    ignore_errors: true
    tags:
      - rule_1.1.1.5
      - filesystem
      - level1
      - scan

- name: SCAN | 1.1.1.8 | Ensure usb-storage kernel module is not available
  block:
  - name: SCAN | 1.1.1.8 | A | Ensure usb-storage kernel module is not available
    shell: lsmod | grep 'usb_storage'
    register: rule_1_1_1_8_a
    changed_when: false
    failed_when: false

  - name: SCAN | 1.1.1.8 | B | Ensure usb-storage kernel module is not available
    shell: modprobe -n -v usb-storage
    register: rule_1_1_1_8_b
    changed_when: false
    failed_when: false

  - set_fact:
      rule_1_1_1_8_result: true
    when: rule_1_1_1_8_a.rc != 0 and (rule_1_1_1_8_b.rc != 0 or 'install' in rule_1_1_1_8_b.stdout)
  - set_fact:
      all_results: "{{ all_results|combine({'1.1.1.8':rule_1_1_1_8_result|default(false)}) }}"
    when: rhel9cis_rule_1_1_1_8
    ignore_errors: true
    tags:
      - rule_1.1.1.8
      - filesystem
      - level1
      - scan


  - name: SCAN | 1.1.2.1.1 | Ensure /tmp is a separate partition (Automated)
    block:
    - name: SCAN | 1.1.2.1.1 | Ensure /tmp is a Separate Partition
      shell: findmnt -kn /tmp
      register: rule_1_1_2_1_1
      changed_when: false
      failed_when: false

    - set_fact:
        rule_1_1_2_1_1_result: true
      when: rule_1_1_2_1_1.rc == 0
    - set_fact:
        all_results: "{{ all_results|combine({'1.1.2.1.1':rule_1_1_2_1_1_result|default(false)}) }}"
    when: rhel9cis_rule_1_1_2_1_1
    ignore_errors: true
    tags:
      - rule_1.1.2.1.1
      - partition
      - level1
      - scan

  - name: SCAN | 1.1.2.1.2 | Ensure nodev option set on /tmp partition
    block:
    - name: SCAN | 1.1.2.1.2 | Ensure nodev option set on /tmp partition
      shell: findmnt -kn /tmp | grep -v nodev
      register: rule_1_1_2_1_2
      changed_when: false
      failed_when: false

    - set_fact:
        rule_1_1_2_1_2_result: true
      when: rule_1_1_2_1_2.rc != 0
    - set_fact:
        all_results: "{{ all_results|combine({'1.1.2.1.2':rule_1_1_2_1_2_result|default(false)}) }}"
    when: rhel9cis_rule_1_1_2_1_2
    ignore_errors: true
    tags:
      - rule_1.1.2.1.2
      - partition
      - level1
      - scan

  - name: SCAN | 1.1.2.1.3 | Ensure nosuid option set on /tmp partition
    block:
    - name: SCAN | 1.1.2.1.3 | Ensure nosuid option set on /tmp partition
      shell: findmnt -kn /tmp | grep -v nosuid
      register: rule_1_1_2_1_3
      changed_when: false
      failed_when: false

    - set_fact:
        rule_1_1_2_1_3_result: true
      when: rule_1_1_2_1_3.rc != 0
    - set_fact:
        all_results: "{{ all_results|combine({'1.1.2.1.3':rule_1_1_2_1_3_result|default(false)}) }}"
    when: rhel9cis_rule_1_1_2_1_3
    ignore_errors: true
    tags:
      - rule_1.1.2.1.3
      - partition
      - level1
      - scan

  - name: SCAN | 1.1.2.1.4 | Ensure noexec option set on /tmp partition
    block:
    - name: SCAN | 1.1.2.1.4 | Ensure noexec option set on /tmp partition
      shell: findmnt -kn /tmp | grep -v noexec
      register: rule_1_1_2_1_4
      changed_when: false
      failed_when: false

    - set_fact:
        rule_1_1_2_1_4_result: true
      when: rule_1_1_2_1_4.rc != 0
    - set_fact:
        all_results: "{{ all_results|combine({'1.1.2.1.4':rule_1_1_2_1_4_result|default(false)}) }}"
    when: rhel9cis_rule_1_1_2_1_4
    ignore_errors: true
    tags:
      - rule_1.1.2.1.4
      - partition
      - level1
      - scan

  - name: SCAN | 1.1.2.2.1 | Ensure /dev/shm is a separate partition
    block:
    - name: SCAN | 1.1.2.2.1 | Ensure /dev/shm is a Separate Partition
      shell: findmnt -kn /dev/shm
      register: rule_1_1_2_2_1
      changed_when: false
      failed_when: false

    - set_fact:
        rule_1_1_2_2_1_result: true
      when: rule_1_1_2_2_1.rc == 0
    - set_fact:
        all_results: "{{ all_results|combine({'1.1.2.2.1':rule_1_1_2_2_1_result|default(false)}) }}"
    when: rhel9cis_rule_1_1_2_2_1
    ignore_errors: true
    tags:
      - rule_1.1.2.2.1
      - partition
      - level1
      - scan

  - name: SCAN | 1.1.2.2.2 | Ensure nodev option set on /dev/shm partition
    block:
    - name: SCAN | 1.1.2.2.2 | Ensure nodev option set on /dev/shm partition
      shell: findmnt -kn /dev/shm | grep -v nodev
      register: rule_1_1_2_2_2
      changed_when: false
      failed_when: false

    - set_fact:
        rule_1_1_2_2_2_result: true
      when: rule_1_1_2_2_2.rc != 0
    - set_fact:
        all_results: "{{ all_results|combine({'1.1.2.2.2':rule_1_1_2_2_2_result|default(false)}) }}"
    when: rhel9cis_rule_1_1_2_2_2
    ignore_errors: true
    tags:
      - rule_1.1.2.2.2
      - partition
      - level1
      - scan

  - name: SCAN | 1.1.2.2.3 | Ensure nosuid option set on /dev/shm partition
    block:
    - name: SCAN | 1.1.2.2.3 | Ensure nosuid option set on /dev/shm partition
      shell: findmnt -kn /dev/shm | grep -v nosuid
      register: rule_1_1_2_2_3
      changed_when: false
      failed_when: false

    - set_fact:
        rule_1_1_2_2_3_result: true
      when: rule_1_1_2_2_3.rc != 0
    - set_fact:
        all_results: "{{ all_results|combine({'1.1.2.2.3':rule_1_1_2_2_3_result|default(false)}) }}"
    when: rhel9cis_rule_1_1_2_2_3
    ignore_errors: true
    tags:
      - rule_1.1.2.2.3
      - partition
      - level1
      - scan

  - name: SCAN | 1.1.2.2.4 | Ensure noexec option set on /dev/shm partition
    block:
    - name: SCAN | 1.1.2.2.4 | Ensure noexec option set on /dev/shm partition
      shell: findmnt -kn /dev/shm | grep -v noexec
      register: rule_1_1_2_2_4
      changed_when: false
      failed_when: false

    - set_fact:
        rule_1_1_2_2_4_result: true
      when: rule_1_1_2_2_4.rc != 0
    - set_fact:
        all_results: "{{ all_results|combine({'1.1.2.2.4':rule_1_1_2_2_4_result|default(false)}) }}"
    when: rhel9cis_rule_1_1_2_2_4
    ignore_errors: true
    tags:
      - rule_1.1.2.2.4
      - partition
      - level1
      - scan

  - name: SCAN | 1.1.2.3.2 | Ensure nodev option set on /home partition
    block:
    - name: SCAN | 1.1.2.3.2 | Ensure nodev option set on /home partition
      shell: findmnt -kn /home | grep -v nodev
      register: rule_1_1_2_3_2
      changed_when: false
      failed_when: false

    - set_fact:
        rule_1_1_2_3_2_result: true
      when: rule_1_1_2_3_2.rc != 0
    - set_fact:
        all_results: "{{ all_results|combine({'1.1.2.3.2':rule_1_1_2_3_2_result|default(false)}) }}"
    when: rhel9cis_rule_1_1_2_3_2
    ignore_errors: true
    tags:
      - rule_1.1.2.3.2
      - partition
      - level1
      - scan

  - name: SCAN | 1.1.2.3.3 | Ensure nosuid option set on /home partition
    block:
    - name: SCAN | 1.1.2.3.3 | Ensure nosuid option set on /home partition
      shell: findmnt -kn /home | grep -v nosuid
      register: rule_1_1_2_3_3
      changed_when: false
      failed_when: false

    - set_fact:
        rule_1_1_2_3_3_result: true
      when: rule_1_1_2_3_3.rc != 0
    - set_fact:
        all_results: "{{ all_results|combine({'1.1.2.3.3':rule_1_1_2_3_3_result|default(false)}) }}"
    when: rhel9cis_rule_1_1_2_3_3
    ignore_errors: true
    tags:
      - rule_1.1.2.3.3
      - partition
      - level1
      - scan
  - name: SCAN | 1.1.2.4.2 | Ensure nodev option set on /var partition
    block:
    - name: SCAN | 1.1.2.4.2 | Ensure nodev option set on /var partition
      shell: findmnt -kn /var | grep -v nodev
      register: rule_1_1_2_4_2
      changed_when: false
      failed_when: false

    - set_fact:
        rule_1_1_2_4_2_result: true
      when: rule_1_1_2_4_2.rc != 0
    - set_fact:
        all_results: "{{ all_results|combine({'1.1.2.4.2':rule_1_1_2_4_2_result|default(false)}) }}"
    when: rhel9cis_rule_1_1_2_4_2
    ignore_errors: true
    tags:
      - rule_1.1.2.4.2
      - partition
      - level1
      - scan

  - name: SCAN | 1.1.2.4.3 | Ensure nosuid option set on /var partition
    block:
    - name: SCAN | 1.1.2.4.3 | Ensure nosuid option set on /var partition
      shell: findmnt -kn /var | grep -v nosuid
      register: rule_1_1_2_4_3
      changed_when: false
      failed_when: false

    - set_fact:
        rule_1_1_2_4_3_result: true
      when: rule_1_1_2_4_3.rc != 0
    - set_fact:
        all_results: "{{ all_results|combine({'1.1.2.4.3':rule_1_1_2_4_3_result|default(false)}) }}"
    when: rhel9cis_rule_1_1_2_4_3
    ignore_errors: true
    tags:
      - rule_1.1.2.4.3
      - partition
      - level1
      - scan

  - name: SCAN | 1.1.2.5.2 | Ensure nodev option set on /var/tmp partition
    block:
    - name: SCAN | 1.1.2.5.2 | Ensure nodev option set on /var/tmp partition
      shell: findmnt -kn /var/tmp | grep -v nodev
      register: rule_1_1_2_5_2
      changed_when: false
      failed_when: false

    - set_fact:
        rule_1_1_2_5_2_result: true
      when: rule_1_1_2_5_2.rc != 0
    - set_fact:
        all_results: "{{ all_results|combine({'1.1.2.5.2':rule_1_1_2_5_2_result|default(false)}) }}"
    when: rhel9cis_rule_1_1_2_5_2
    ignore_errors: true
    tags:
      - rule_1.1.2.5.2
      - partition
      - level1
      - scan

  - name: SCAN | 1.1.2.5.3 | Ensure nosuid option set on /var/tmp partition
    block:
    - name: SCAN | 1.1.2.5.3 | Ensure nosuid option set on /var/tmp partition
      shell: findmnt -kn /var/tmp | grep -v nosuid
      register: rule_1_1_2_5_3
      changed_when: false
      failed_when: false

    - set_fact:
        rule_1_1_2_5_3_result: true
      when: rule_1_1_2_5_3.rc != 0
    - set_fact:
        all_results: "{{ all_results|combine({'1.1.2.5.3':rule_1_1_2_5_3_result|default(false)}) }}"
    when: rhel9cis_rule_1_1_2_5_3
    ignore_errors: true
    tags:
      - rule_1.1.2.5.3
      - partition
      - level1
      - scan

  - name: SCAN | 1.1.2.5.4 | Ensure noexec option set on /var/tmp partition
    block:
    - name: SCAN | 1.1.2.5.4 | Ensure noexec option set on /var/tmp partition
      shell: findmnt -kn /var/tmp | grep -v noexec
      register: rule_1_1_2_5_4
      changed_when: false
      failed_when: false

    - set_fact:
        rule_1_1_2_5_4_result: true
      when: rule_1_1_2_5_4.rc != 0
    - set_fact:
        all_results: "{{ all_results|combine({'1.1.2.5.4':rule_1_1_2_5_4_result|default(false)}) }}"
    when: rhel9cis_rule_1_1_2_5_4
    ignore_errors: true
    tags:
      - rule_1.1.2.5.4
      - partition
      - level1
      - scan

  - name: SCAN | 1.1.2.6.2 | Ensure nodev option set on /var/log partition
    block:
    - name: SCAN | 1.1.2.6.2 | Ensure nodev option set on /var/log partition
      shell: findmnt -kn /var/log | grep -v nodev
      register: rule_1_1_2_6_2
      changed_when: false
      failed_when: false

    - set_fact:
        rule_1_1_2_6_2_result: true
      when: rule_1_1_2_6_2.rc != 0
    - set_fact:
        all_results: "{{ all_results|combine({'1.1.2.6.2':rule_1_1_2_6_2_result|default(false)}) }}"
    when: rhel9cis_rule_1_1_2_6_2
    ignore_errors: true
    tags:
      - rule_1.1.2.6.2
      - partition
      - level1
      - scan

  - name: SCAN | 1.1.2.6.3 | Ensure nosuid option set on /var/log partition
    block:
    - name: SCAN | 1.1.2.6.3 | Ensure nosuid option set on /var/log partition
      shell: findmnt -kn /var/log | grep -v nosuid
      register: rule_1_1_2_6_3
      changed_when: false
      failed_when: false

    - set_fact:
        rule_1_1_2_6_3_result: true
      when: rule_1_1_2_6_3.rc != 0
    - set_fact:
        all_results: "{{ all_results|combine({'1.1.2.6.3':rule_1_1_2_6_3_result|default(false)}) }}"
    when: rhel9cis_rule_1_1_2_6_3
    ignore_errors: true
    tags:
      - rule_1.1.2.6.3
      - partition
      - level1
      - scan

  - name: SCAN | 1.1.2.6.4 | Ensure noexec option set on /var/log partition
    block:
    - name: SCAN | 1.1.2.6.4 | Ensure noexec option set on /var/log partition
      shell: findmnt -kn /var/log | grep -v noexec
      register: rule_1_1_2_6_4
      changed_when: false
      failed_when: false

    - set_fact:
        rule_1_1_2_6_4_result: true
      when: rule_1_1_2_6_4.rc != 0
    - set_fact:
        all_results: "{{ all_results|combine({'1.1.2.6.4':rule_1_1_2_6_4_result|default(false)}) }}"
    when: rhel9cis_rule_1_1_2_6_4
    ignore_errors: true
    tags:
      - rule_1.1.2.6.4
      - partition
      - level1
      - scan

  - name: SCAN | 1.1.2.7.2 | Ensure nodev option set on /var/log/audit partition
    block:
    - name: SCAN | 1.1.2.7.2 | Ensure nodev option set on /var/log/audit partition
      shell: findmnt -kn /var/log/audit | grep -v nodev
      register: rule_1_1_2_7_2
      changed_when: false
      failed_when: false

    - set_fact:
        rule_1_1_2_7_2_result: true
      when: rule_1_1_2_7_2.rc != 0
    - set_fact:
        all_results: "{{ all_results|combine({'1.1.2.7.2':rule_1_1_2_7_2_result|default(false)}) }}"
    when: rhel9cis_rule_1_1_2_7_2
    ignore_errors: true
    tags:
      - rule_1.1.2.7.2
      - partition
      - level1
      - scan

  - name: SCAN | 1.1.2.7.3 | Ensure nosuid option set on /var/log/audit partition
    block:
    - name: SCAN | 1.1.2.7.3 | Ensure nosuid option set on /var/log/audit partition
      shell: findmnt -kn /var/log/audit | grep -v nosuid
      register: rule_1_1_2_7_3
      changed_when: false
      failed_when: false

    - set_fact:
        rule_1_1_2_7_3_result: true
      when: rule_1_1_2_7_3.rc != 0
    - set_fact:
        all_results: "{{ all_results|combine({'1.1.2.7.3':rule_1_1_2_7_3_result|default(false)}) }}"
    when: rhel9cis_rule_1_1_2_7_3
    ignore_errors: true
    tags:
      - rule_1.1.2.7.3
      - partition
      - level1
      - scan

  - name: SCAN | 1.1.2.7.4 | Ensure noexec option set on /var/log/audit partition
    block:
    - name: SCAN | 1.1.2.7.4 | Ensure noexec option set on /var/log/audit partition
      shell: findmnt -kn /var/log/audit | grep -v noexec
      register: rule_1_1_2_7_4
      changed_when: false
      failed_when: false

    - set_fact:
        rule_1_1_2_7_4_result: true
      when: rule_1_1_2_7_4.rc != 0
    - set_fact:
        all_results: "{{ all_results|combine({'1.1.2.7.4':rule_1_1_2_7_4_result|default(false)}) }}"
    when: rhel9cis_rule_1_1_2_7_4
    ignore_errors: true
    tags:
      - rule_1.1.2.7.4
      - partition
      - level1
      - scan