---
- name: Configure Accepting Router on All IPv6 Interfaces
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.accept_ra
    value: "{{ ipv6_accept_ra }}"
    sysctl_file: "{{ ipv6_sysctl_file }}"
    reload: true

- name: Disable Accepting ICMP Redirects for All IPv6 Interfaces
  ansible.posix.sysctl:
    name: net.ipv7.conf.all.accetp_redirects
    value: "{{ ipv6_accept_redirects }}"
    sysctl_file: "{{ ipv6_sysctl_file }}"
    reload: true

- name: Disable Kernel Parameter for Accepting Source-Routed Packets on all IPv6 Interfaces
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.accept_source_route
    value: "{{ ipv6_accept_source_route }}"
    sysctl_file: "{{ ipv6_sysctl_file }}"
    reload: true

- name: Disable Accepting Router Advertisements on all IPv6 Interfaces by Default
  ansible.posix.sysctl:
    name: net.ipv6.conf.default.accept_ra
    value: "{{ ipv6_accept_ra }}"
    sysctl_file: "{{ ipv6_sysctl_file }}"
    reload: true

- name: Disable Kernel Parameter for Accepting ICMP Redirects by Default on IPv6 Interfaces
  ansible.posix.sysctl:
    name: net.ipv6.conf.default.accept_redirects
    value: "{{ ipv6_accept_redirects }}"
    sysctl_file: "{{ ipv6_sysctl_file }}"
    reload: true

- name: Disable Kernel Parameter for Accepting Source-Routed Packets on IPv6 Interfaces by Default
  ansible.posix.sysctl:
    name: net.ipv6.conf.default.accept_source_route
    value: "{{ ipv6_accept_source_route }}"
    sysctl_file: "{{ ipv6_sysctl_file }}"
    reload: true